### ISSUE TITLE
Code Review: @ananyasingh7

### ISSUE THREAD

**Issue by ananyasingh7** [RD345/CS435-Project-2#1] opened 2020-04-14 05:43 UTC
![image](https://user-images.githubusercontent.com/28812354/79189555-110e6300-7df0-11ea-8c68-8688a2f3e1d2.png)

(graph.py) Hey, I don't really understand the point of this function, to be honest. From what it seems you are trying to either return the value of the node OR just return the node itself. But on line 19, target is str, that is just checking if they are the same object instance. You can simply remove this function and still be fine I believe.

**Comment by ananyasingh7** [comment] 2020-04-14 05:50
![image](https://user-images.githubusercontent.com/28812354/79190214-b413ac80-7df1-11ea-8d3c-c97261006715.png)
(graph.py) You don't need "node1, node2 = self.getNode(node1), self.getNode(node2)" because it's repetitive and it's already declared as a node and you should probably check if node1 does not exist in node2 neighbors before you connect them (vice versa)... however that isn't a BIG problem.

**Comment by ananyasingh7** [comment] 2020-04-14 05:52
![image](https://user-images.githubusercontent.com/28812354/79190455-63e91a00-7df2-11ea-8a7a-2c9caa95e8f3.png)
(graph.py) Your way works. However, it might be more efficient to do "if conn in node1.connections then remove" instead of doing two for-loops.

**Comment by ananyasingh7** [comment] 2020-04-14 05:55
![image](https://user-images.githubusercontent.com/28812354/79190606-ba565880-7df2-11ea-84bb-647b41c94df3.png)
(graph.py) 
Two things: 1) for getNodes, you are returning a list instead of a set. A list can have duplicate nodes and that is a problem because every node in a graph needs to be unique. A set returns a list of unique nodes in a list! Here is more documentation: https://docs.python.org/2/library/sets.html 
                    2) Honestly, addBirectionalEdge (and other functions) are not used in the class, then you should remove it before you submit it and I also believe it makes things more confusing. However, that is just a suggestion.

**Comment by ananyasingh7** [comment] 2020-04-14 05:57
(graph.py) remove unnecessary comments from the bottom on the page.

**Comment by ananyasingh7** [comment] 2020-04-14 06:09
![image](https://user-images.githubusercontent.com/28812354/79191239-21c0d800-7df4-11ea-85e0-8a98c7bf2588.png)
(directedGraph.py) Just 2 points:
1) for adding Directed Edge function, you should check first that the first node doesn't have the second node already as a neighbor. Technically, suppose I had Node A and Node B, using your code, I could technically continue to connect Node A to Node B 10,000 times if I wanted to and if I printed out Node A's neighbor, I would see Node B 10,000 times because you have a list instead of a set to hold your neighbors. 
2) Fix getAllNodes to return a set instead of a list!

**Comment by ananyasingh7** [comment] 2020-04-14 06:34
![image](https://user-images.githubusercontent.com/28812354/79193355-736b6180-7df8-11ea-903d-b0bf1837a026.png)
(TopSort.java) ahh i only did up to here and I can't grade this! oh well

**Comment by ananyasingh7** [comment] 2020-04-14 06:49
![image](https://user-images.githubusercontent.com/28812354/79193629-04dad380-7df9-11ea-8615-87b9d4a71ff2.png)
(graphSearch.py) 
I like your use of closers, I only know a few people at NJIT who use them! That being said, a few points:

1) In your parameters, why are start_node and end_node set to 0, 1 respectively? I feel like that's unnecessary.  
2) You also don't need line 26 where you are redeclaring your node as a node. 
3) In your helper function, instead of "curr_node.val == str(end_node)", you could do curr_node == end_node.

**Comment by ananyasingh7** [comment] 2020-04-14 07:15
![image](https://user-images.githubusercontent.com/28812354/79195145-c5fa4d00-7dfb-11ea-89c3-4b8d9cfe235b.png)
(graphSearch.py)
1) In my opinion, you don't need lines 57 to 60, you could just simply return the list "visited". 
2) I *believe* you can make your while loop smaller and *maybe* more efficient by pretty much reworking the if-else statement and switching it with the for-loop. I am thinking along the lines of (for the neighbor in curr_node.connections): stack.append(neighbor) if neighbor.val == curr.node etc. This might be more efficient but test it if you want to change it.

**Comment by ananyasingh7** [comment] 2020-04-14 07:37
![image](https://user-images.githubusercontent.com/28812354/79197197-56865c80-7dff-11ea-93fc-e82bcc32a40c.png)
(graphSearch.py)
1. Unfortunately, this is wrong from the start because the ONLY parameter this function requires is the graph, no start, and the end node. You don't need to start and end for a traversal. 
2. Because of the point made above, you don't need lines 102 and 103.
3. You need to return the visited array, get rid of return False on line 112. 
4. Because of the points above, tweak your BFT to become a traversal. You are pretty close.

**Comment by ananyasingh7** [comment] 2020-04-14 07:40
![image](https://user-images.githubusercontent.com/28812354/79198461-820a4680-7e01-11ea-8aca-65f9fa6e03ea.png)
(graphSearch.py)
1. Exactly like the issue above, this isn't a traversal. Tweak your BFT to become a traversal.

**Comment by ananyasingh7** [comment] 2020-04-14 07:41
Other than that, I am done with code review. Please message me if something I said doesn't make sense or if you have a question! GLHF!

**Comment by RD345** [comment] 2020-04-15 17:53
> ![image](https://user-images.githubusercontent.com/28812354/79189555-110e6300-7df0-11ea-8c68-8688a2f3e1d2.png)
> 
> (graph.py) Hey, I don't really understand the point of this function, to be honest. From what it seems you are trying to either return the value of the node OR just return the node itself. But on line 19, target is str, that is just checking if they are the same object instance. You can simply remove this function and still be fine I believe.

So for this, I will add a description for the function to make it less confusing, but in short, this function is necessary since I use it to return a Node object from either the node object itself, or a string or int value. This function _always_ returns a node, and never returns just a value. If the target is a node, it will just return it. If the target is a node value, whether it is a string or int (hence the target=str(target)), it will search for it and then return the Node object.

**Comment by RD345** [comment] 2020-04-15 18:00
> ![image](https://user-images.githubusercontent.com/28812354/79190214-b413ac80-7df1-11ea-8d3c-c97261006715.png)
> (graph.py) You don't need "node1, node2 = self.getNode(node1), self.getNode(node2)" because it's repetitive and it's already declared as a node and you should probably check if node1 does not exist in node2 neighbors before you connect them (vice versa)... however that isn't a BIG problem.

As for this, this function does not assume that the inputs are going to be node objects, and thus the getNode function is called. In python, the inputs types are not declared, and thus not guaranteed. This function always returns a Node object if it exists, so this ensures that the function will execute properly.

**Comment by RD345** [comment] 2020-04-15 18:05
> ![image](https://user-images.githubusercontent.com/28812354/79190455-63e91a00-7df2-11ea-8a7a-2c9caa95e8f3.png)
> (graph.py) Your way works. However, it might be more efficient to do "if conn in node1.connections then remove" instead of doing two for-loops.

This would be a good suggestion if the connections were stored in the same array, but in my project, the connections are stored within each node _itself_, and thus I must loop  through each node's connections individually.

**Comment by RD345** [comment] 2020-04-15 18:22
> ![image](https://user-images.githubusercontent.com/28812354/79190606-ba565880-7df2-11ea-84bb-647b41c94df3.png)
> (graph.py)
> Two things: 1) for getNodes, you are returning a list instead of a set. A list can have duplicate nodes and that is a problem because every node in a graph needs to be unique. A set returns a list of unique nodes in a list! Here is more documentation: https://docs.python.org/2/library/sets.html
> 2) Honestly, addBirectionalEdge (and other functions) are not used in the class, then you should remove it before you submit it and I also believe it makes things more confusing. However, that is just a suggestion.

1) Thank you for the set suggestion, I did not know about sets, and I will change this function so that it returns one. However, my project should already ensure that there are no duplicates, and if there were, the rest of this project might not work anyway. Edit: Done [here](https://github.com/RD345/CS435-Project-2/commit/92efcbfb52385f88686af94f813b872d8a1af65d)
2) Yes you're right that this function is not necessary, but it is a shorthand way to add two edges between two nodes, and is named in a way that indicates that function. It mirrors addUndirectedEdge, but is directed instead. It is used in both the DAG and the unWeightedGraph. 
Edit: I have now removed this function [here](https://github.com/RD345/CS435-Project-2/commit/d0bfba76178b94a2e430aec4700634e516a09ff6)

**Comment by RD345** [comment] 2020-04-15 18:28
> ![image](https://user-images.githubusercontent.com/28812354/79191239-21c0d800-7df4-11ea-85e0-8a98c7bf2588.png)
> (directedGraph.py) Just 2 points:
> 
> 1. for adding Directed Edge function, you should check first that the first node doesn't have the second node already as a neighbor. Technically, suppose I had Node A and Node B, using your code, I could technically continue to connect Node A to Node B 10,000 times if I wanted to and if I printed out Node A's neighbor, I would see Node B 10,000 times because you have a list instead of a set to hold your neighbors.
> 2. Fix getAllNodes to return a set instead of a list!

1) I already have a handler for duplicates in the addEdge function itself -- if the edge already exists it will not create a new one.
2) Will fix, thanks! Edit: fixed [here](https://github.com/RD345/CS435-Project-2/commit/92efcbfb52385f88686af94f813b872d8a1af65d)

**Comment by RD345** [comment] 2020-04-15 18:30
> ![image](https://user-images.githubusercontent.com/28812354/79193355-736b6180-7df8-11ea-903d-b0bf1837a026.png)
> (TopSort.java) ahh i only did up to here and I can't grade this! oh well

I also was unable to finish this, no worries.

**Comment by RD345** [comment] 2020-04-15 18:42
> ![image](https://user-images.githubusercontent.com/28812354/79193629-04dad380-7df9-11ea-8615-87b9d4a71ff2.png)
> (graphSearch.py)
> I like your use of closers, I only know a few people at NJIT who use them! That being said, a few points:
> 
> 1. In your parameters, why are start_node and end_node set to 0, 1 respectively? I feel like that's unnecessary.
> 2. You also don't need line 26 where you are redeclaring your node as a node.
> 3. In your helper function, instead of "curr_node.val == str(end_node)", you could do curr_node == end_node.

0) Thanks! I actually didn't even know what a closure was until you said this, I ended up with this solution after struggling with how to find if the node was already found in the subcalls. I learned something today.
1) Perhaps you are not that familiar with python, but these are default values, and are only used if the args are not provided. I put these here for easy testing.
2) As I mentioned in previous replies, the node inputs to the function are not assumed to be Node objects, this function takes a possibility space of (Node, string, int) and returns only Node (or None). This allows the function to execute as intended.
3) The string function here ensures that this comparison does not fail if the input was an integer, (which the default value is), and not a string, since all node values are stored as strings.

**Comment by RD345** [comment] 2020-04-15 18:56
> ![image](https://user-images.githubusercontent.com/28812354/79195145-c5fa4d00-7dfb-11ea-89c3-4b8d9cfe235b.png)
> (graphSearch.py)
> 
> 1. In my opinion, you don't need lines 57 to 60, you could just simply return the list "visited".
> 2. I _believe_ you can make your while loop smaller and _maybe_ more efficient by pretty much reworking the if-else statement and switching it with the for-loop. I am thinking along the lines of (for the neighbor in curr_node.connections): stack.append(neighbor) if neighbor.val == curr.node etc. This might be more efficient but test it if you want to change it.

1) Something I've realized is that I misunderstood this question, I made this function so that it _searches_ for a node and returns the path to it if found. This return is a result of that, it will give the path if it was found, and False if it was not. So for the actual question, you're completely right @ananyasingh7. However for my "DFSRecSearch" as it were, I need this statement.
2) I've tried looking at this, I'm not really sure what you mean, but I'm cleaning up the code to make it more explicit. I don't know of any way to do this without the if block.

**Comment by RD345** [comment] 2020-04-15 19:01
> ![image](https://user-images.githubusercontent.com/28812354/79197197-56865c80-7dff-11ea-93fc-e82bcc32a40c.png)
> (graphSearch.py)
> 
> 1. Unfortunately, this is wrong from the start because the ONLY parameter this function requires is the graph, no start, and the end node. You don't need to start and end for a traversal.
> 2. Because of the point made above, you don't need lines 102 and 103.
> 3. You need to return the visited array, get rid of return False on line 112.
> 4. Because of the points above, tweak your BFT to become a traversal. You are pretty close.

Yes, I misread this question and created a BFT search instead of a traversal. I wasted so much time on this and it was actually only a traversal...sigh. I actually did this for every traversal question by mistake. These will all have to be redone. Thanks for catching this!
Edit: Completed [here](https://github.com/RD345/CS435-Project-2/commit/a0d15e7ec5e1bf1fd48de6fc2e7b25fc4ec1f638)

**Comment by RD345** [comment] 2020-04-15 19:02
> ![image](https://user-images.githubusercontent.com/28812354/79198461-820a4680-7e01-11ea-8aca-65f9fa6e03ea.png)
> (graphSearch.py)
> 
> 1. Exactly like the issue above, this isn't a traversal. Tweak your BFT to become a traversal.

Same as comment above, all my traversals are searches instead. This will be fixed.
Edit: Completed [here](https://github.com/RD345/CS435-Project-2/commit/a0d15e7ec5e1bf1fd48de6fc2e7b25fc4ec1f638)

**Comment by RD345** [comment] 2020-04-15 22:07
Comments to Address:
- [x] [1](https://github.com/RD345/CS435-Project-2/issues/1#issue-599311807)
- [x] [2](https://github.com/RD345/CS435-Project-2/issues/1#issuecomment-613239374)
- [x] [3](https://github.com/RD345/CS435-Project-2/issues/1#issuecomment-613239985)
- [x] [4](https://github.com/RD345/CS435-Project-2/issues/1#issuecomment-613240856)
- [x] [5](https://github.com/RD345/CS435-Project-2/issues/1#issuecomment-613244851)
- [x] [6](https://github.com/RD345/CS435-Project-2/issues/1#issuecomment-613253174)
- [x] [7](https://github.com/RD345/CS435-Project-2/issues/1#issuecomment-613258099)
- [x] [8](https://github.com/RD345/CS435-Project-2/issues/1#issuecomment-613268092)
- [x] [9](https://github.com/RD345/CS435-Project-2/issues/1#issuecomment-613277328)
- [x] [10](https://github.com/RD345/CS435-Project-2/issues/1#issuecomment-613278650)

**Comment by RD345** [comment] 2020-04-18 18:56
All changes and responses complete.

**Closed as completed by RD345** 2020-04-18 18:56 UTC
Labels: bug, enhancement
